FROM python:3.12-slim-bullseye AS builder

WORKDIR /app

COPY .env README.md pyproject.toml poetry.lock .
COPY streamlit_app/ streamlit_app/

RUN python -m pip install poetry==1.8.4 \
    && poetry config virtualenvs.in-project true \
    && poetry install --no-root

FROM python:3.12-slim-bullseye
COPY --from=builder /app /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV BASE_URL="http://app:4242/api/v1"

WORKDIR /app/streamlit_app
